### DISCUSSION TITLE
Handle & Label Behavior (always show float)

### DISCUSSION THREAD

**Discussion by stevegiorgi** [simeydotme/svelte-range-slider-pips#114] [Q&A] [answered]
How can we make the handle + labels always visible and also have the ability to use the handles + labels as slider controls?

Edit: I've accomplished this by simply updating the CSS:

```css
.rangeHandle .rangeFloat {
    top: -1em;
    transform: translate(-50%, -100%) rotateX(0deg);
    opacity: 1;
}

.rangeFloat {
    pointer-events: auto;
}
```

**Comment by simeydotme** [comment]
> Edit: I've accomplished this by simply updating the CSS:

```css
.rangeHandle .rangeFloat {
    top: -1em;
    transform: translate(-50%, -100%) rotateX(0deg);
    opacity: 1;
}

.rangeFloat {
    pointer-events: auto;
}
```
